### ISSUE TITLE
DistributedDataParallel and Apex support?

### ISSUE THREAD

**Issue by radao** [pytorchbearer/torchbearer#614]
Are there any plans to include DistributedDataParallel and Apex support?

**Comment by MattPainter01** [comment]
They are definitely things that we would like to support. I'm not entirely sure how supported they are at the moment, will need some testing to be sure. We'll have a look over the next couple of weeks to see how feasible it is. 

In the mean time, feel free to have a go and put in a pr if you get anything working.

**Comment by MattPainter01** [comment]
I've had a quick look into both distributed data parallel and Apex and I think we support them for most basic stuff, although I haven't used either enough to tell if more advanced applications will be a problem. 

I've added an Apex closure in #618 for convenience to do the context manager loss scaling that the newer Apex api requires and I also added a quick note/example for them in the same pr. 

Thanks for the issue.
