### ISSUE TITLE
regarding HBox in colab 

### ISSUE THREAD

**Issue by vainaijr** [pytorchbearer/torchbearer#635]
I get this as output, in history tutorial, in colab, should this be something different?

HBox(children=(IntProgress(value=0, description='18/20(t)', max=1), HTML(value='')))

**Comment by ethanwharris** [comment]
Yeah, this happens whenever output from the tqdm_notebook variant is reloaded. If you re-run it should fix it. If you face other problems, use `%torchbearer normal` after the import to switch to normal tqdm. Hope that helps!
