### ISSUE TITLE
PyCM result unavailable to save to csv format

### ISSUE THREAD

**Issue by BartekKrzepkowski** [pytorchbearer/torchbearer#647]
I suppose pycm doesn't support '**overall_param**' anymore within save_csv method.

![pycm](https://user-images.githubusercontent.com/19740116/68950196-f17cfb00-07bb-11ea-98f5-c183a8d38bf6.png)

**Comment by ethanwharris** [comment]
Hi, thanks for your issue! That's unfortunate, best solution would be to replace this method with one that takes `*args` and `**kwargs`. I'll aim to fix within a couple of days.
