### ISSUE TITLE
KeyError: 'val_acc'

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [pytorchbearer/torchbearer#655]
Hi Guys,

`EarlyStopping` has the same problem we had with #650 . Basically, when we evaluate everything will explode because `val_loss` does not exist. 

```python
    trial = Trial(cnn, optimizer, loss, metrics=['acc', 'loss'],
                  callbacks=[

                    EarlyStopping(monitor='val_acc', patience=5, mode='max'),
    ]).to(device)
    trial.with_generators(train_generator=train_dl,
                          val_generator=val_dl, test_generator=test_dl)
    # history = trial.run(params['epochs'], verbose=1)
    preds = trial.evaluate(data_key=torchbearer.TEST_DATA)

```

Error 

```
  File "C:\Users\Francesco\Anaconda3\envs\dl\lib\site-packages\torchbearer\callbacks\early_stopping.py", line 72, in step
    current = state[torchbearer.METRICS][self.monitor]
KeyError: 'val_acc'
```

From `EarlyStoppin` Code

```python

  def step(self, state):
        current = state[torchbearer.METRICS][self.monitor] # <-- ERROR IS HERE
        if self.monitor_op(current - self.min_delta, self.best):
            self.best = current
            self.wait = 0
        else:
            self.wait += 1
            if self.wait >= self.patience:
                state[torchbearer.STOP_TRAINING] = True

``` 
We should do the same check we have done before. Probably other callbacks have the same error. I would like to use torchbearer for my project, can we make a super quick fix and push a new release? 

The best thing is to think about a more robust method to ensure code won't crash in these occasions.

Thank you.

Cheers,

Francesco Saverio

**Comment by MattPainter01** [comment]
Yeah, we used to prefer errors over warnings in cases like this so things didn't silently fail, make debugging easier etc. I can see that for callbacks like early stopping this is particularly annoying though since the main training obviously worked fine. 

I'll make all the checks use some standard check with warnings and we'll put out another minor version afterwards.

**Comment by FrancescoSaverioZuppichini** [comment]
Maybe one easy test you can add is to just run one model on a small dataset with all the callbacks enable. I totally agree to crash is better than silently fail
