### ISSUE TITLE
running_loss vs loss

### ISSUE THREAD

**Issue by yongduek** [pytorchbearer/torchbearer#662]
Thanks a lot for the wonderful library.

Could anyone please provide exact difference in definitions of `loss` and `running_loss`, or likewise `acc` and `running_acc` in the history record returned from `trial.run(10,verbose=1)`?

I tried to find it in the document site, but could not see any.

many thanks for the help.

**Comment by ethanwharris** [comment]
Sure! The `running_` variants are averages over the last 50 batches or so (I don't remeber what the exact number is). Whereas the plain `acc` / `loss` are the averages over the whole epoch. See [here](https://torchbearer.readthedocs.io/en/latest/code/metrics.html#torchbearer.metrics.decorators.running_mean) for running metrics and [here](https://torchbearer.readthedocs.io/en/latest/code/metrics.html#torchbearer.metrics.decorators.mean) for the others.

I hope that helps!
