### ISSUE TITLE
skorch export functionality

### ISSUE THREAD

**Issue by MattPainter01** [pytorchbearer/torchbearer#76]

**Comment by ottonemo** [comment]
Maybe you can just provide export functionality so that a model can be imported into [skorch](https://github.com/dnouri/skorch) which already provides an sklearn interface?

**Comment by ethanwharris** [comment]
@ottonemo @MattPainter01 skorch export is a nice idea. Cross Val, Grid Seacrh etc. would be very useful. Can just wrap the torchbearer Model in a skorch Net instance so that metrics / callbacks all get called under the hood. Ill look into it :)

**Comment by ethanwharris** [comment]
This seems unlikely
